config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin_room do
    resources :users
    resources :member_registration_requests, only: %i[index show] do
      put :accept, on: :member
      put :refuse, on: :member
    end
    resources :members do
      resources :memberships, except: %i[index]
    end
    resources :membership_forms
    resources :subscriptions, except: %i[edit] do
      get :preview, on: :member
      resources :payments, except: %i[index]
    end
    resources :producers do
      resources :contracts, except: %i[index]
    end

    root to: 'welcome#index'
  end

  namespace :member_room do
    root to: 'welcome#index'
    resources :subscriptions, only: %i[index show]
  end

  devise_for :users, path: 'admin_room'
  devise_for :members, path: 'member_room'

  delete :members_sign_up, to: 'members_sign_up#destroy'
  scope :members_sign_up, as: :members_sign_up do
    get :step_1, to: 'members_sign_up#step_1'
    post :step_1, to: 'members_sign_up#save_step_1'
    get :step_2, to: 'members_sign_up#step_2'
    patch :step_2, to: 'members_sign_up#save_step_2'
    get :step_3, to: 'members_sign_up#step_3'
    patch :step_3, to: 'members_sign_up#save_step_3'
    get :step_4, to: 'members_sign_up#step_4'
  end

  root to: 'welcome#index'
end

app/controllers/member_room/subscriptions_controller.rb
# frozen_string_literal: true

module MemberRoom
  class SubscriptionsController < MemberRoomController
    load_and_authorize_resource through: :current_member

    # GET /subscriptions
    # GET /subscriptions.json
    def index
      @subscriptions = current_member.subscriptions.order(subscribed_at: :desc).page
    end

    # GET /subscriptions/1
    # GET /subscriptions/1.json
    def show
      render layout: false
    end
  end
end

app/controllers/member_room/welcome_controller.rb
# frozen_string_literal: true

module MemberRoom
  class WelcomeController < MemberRoomController
    def index
    end
  end
end

app/controllers/member_room_controller.rb
# frozen_string_literal: true

class MemberRoomController < ApplicationController
  before_action :authenticate_member!
  alias current_user current_member

  rescue_from CanCan::AccessDenied do |exception|
    Rails.logger.debug "Access denied on #{exception.action}"\
      " #{exception.subject.inspect}"
    raise
  end

  layout 'member_room/layouts/application'
end

app/views/member_room/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
  <%= link_to safe_join([t('project.name_html'), ' / ', t('project.member')]), member_room_root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbars" aria-controls="navbars" aria-expanded="false" aria-label="<%= t('actions.toggle_menu') %>">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-collapse collapse" id="navbars">
    <% if member_signed_in? %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to t('navbar.my_contracts'), member_room_subscriptions_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="memberMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t('project.welcome_html', user: current_member.first_name) %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="memberMenuLink">
          <%= link_to(t('devise.shared.links.sign_out_html'), destroy_session_path(current_member), method: :delete, class: 'dropdown-item') %>
        </div>
      </li>
    </ul>
    <% else %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to t('navbar.back_to_the_root_html'), root_path, class: 'nav-link' %>
      </li>
    </ul>
    <% end %>
  </div>
</nav>