config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin_room do
    resources :users
    resources :member_registration_requests, only: %i[index show] do
      put :accept, on: :member
      put :refuse, on: :member
    end
    resources :members do
      resources :memberships, except: %i[index]
    end
    resources :membership_forms
    resources :subscriptions, except: %i[edit] do
      get :preview, on: :member
      resources :payments, except: %i[index]
    end
    resources :producers do
      resources :contracts, except: %i[index]
    end

    root to: 'welcome#index'
  end

  namespace :member_room do
    root to: 'welcome#index'
    resources :subscriptions, only: %i[index show]
  end

  devise_for :users, path: 'admin_room'
  devise_for :members, path: 'member_room'

  delete :members_sign_up, to: 'members_sign_up#destroy'
  scope :members_sign_up, as: :members_sign_up do
    get :step_1, to: 'members_sign_up#step_1'
    post :step_1, to: 'members_sign_up#save_step_1'
    get :step_2, to: 'members_sign_up#step_2'
    patch :step_2, to: 'members_sign_up#save_step_2'
    get :step_3, to: 'members_sign_up#step_3'
    patch :step_3, to: 'members_sign_up#save_step_3'
    get :step_4, to: 'members_sign_up#step_4'
  end

  root to: 'welcome#index'
end

app/controllers/admin_room/contracts_controller.rb
# frozen_string_literal: true

module AdminRoom
  class ContractsController < AdminRoomController
    load_and_authorize_resource :producer
    load_and_authorize_resource :contract, through: :producer

    # GET /producers/1/contracts/1
    # GET /producers/1/contracts/1.json
    def show
    end

    # GET /producers/1/contracts/new
    def new
      @contract = Contract.new
    end

    # GET /producers/1/contracts/1/edit
    def edit
    end

    # POST /producers/1/contracts
    # POST /producers/1/contracts.json
    def create
      @contract = Contract.new(contract_params.merge(producer: @producer))

      respond_to do |format|
        if @contract.save
          format.html { redirect_to admin_room_producer_contract_path(id: @contract.id, producer_id: @producer.id), notice: t('.created') }
          format.json { render :show, status: :created, location: @contract }
        else
          format.html { render :new }
          format.json { render json: @contract.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /producers/1/contracts/1
    # PATCH/PUT /producers/1/contracts/1.json
    def update
      respond_to do |format|
        if @contract.update(contract_params)
          format.html { redirect_to admin_room_producer_contract_path(id: @contract.id, producer_id: @producer.id), notice: t('.updated') }
          format.json { render :show, status: :ok, location: @contract }
        else
          format.html { render :edit }
          format.json { render json: @contract.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /producers/1/contracts/1
    # DELETE /producers/1/contracts/1.json
    def destroy
      @contract.destroy
      respond_to do |format|
        format.html { redirect_to admin_room_producer_path(@producer), notice: t('.destroyed') }
        format.json { head :no_content }
      end
    end

    private

    # Never trust parameters from the scary internet, only allow
    # the white list through.
    def contract_params
      params.require(:contract).permit(:title, :content)
    end
  end
end

app/controllers/admin_room/member_registration_requests_controller.rb
# frozen_string_literal: true

module AdminRoom
  class MemberRegistrationRequestsController < AdminRoomController
    load_and_authorize_resource

    # GET /member_registration_requests
    # GET /member_registration_requests.json
    def index
      @member_registration_requests = MemberRegistrationRequest.not_accepted_or_refused_yet
                                                               .order(created_at: :desc)
                                                               .page
    end

    # GET /member_registration_requests/1
    # GET /member_registration_requests/1.json
    def show
    end

    # PUT /member_registration_requests/1/accept
    # PUT /member_registration_requests/1/accept.json
    def accept # rubocop:disable Metrics/MethodLength
      respond_to do |format|
        if @member_registration_request.accept(user: current_user)
          format.html { redirect_to admin_room_member_registration_request_path(id: @member_registration_request.id), notice: t('.accepted') }
          format.json { render :show, status: :ok, location: @member_registration_request }
        else
          format.html do
            flash[:alert] = @member_registration_request.errors.full_messages.join(', ')
            render :show
          end
          format.json { render json: @member_registration_request.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /member_registration_requests/1/refuse
    # PUT /member_registration_requests/1/refuse.json
    def refuse # rubocop:disable Metrics/MethodLength
      respond_to do |format|
        if @member_registration_request.refuse(user: current_user)
          format.html { redirect_to admin_room_member_registration_request_path(id: @member_registration_request.id), notice: t('.refused') }
          format.json { render :show, status: :ok, location: @member_registration_request }
        else
          format.html do
            flash[:alert] = @member_registration_request.errors.full_messages.join(', ')
            render :show
          end
          format.json { render json: @member_registration_request.errors, status: :unprocessable_entity }
        end
      end
    end
  end
end

app/controllers/admin_room/members_controller.rb
# frozen_string_literal: true

module AdminRoom
  class MembersController < AdminRoomController
    include RemoveBlankPasswordConcern

    load_and_authorize_resource

    # GET /members
    # GET /members.json
    def index
      query = params[:q]

      @members = if query.present?
                   Member.ransack(name_cont: query).result(distinct: true).page
                 else
                   Member.order(:first_name).page
                 end
    end

    # GET /members/1
    # GET /members/1.json
    def show
    end

    # GET /members/new
    def new
      @member = Member.new
    end

    # GET /members/1/edit
    def edit
    end

    # POST /members
    # POST /members.json
    def create
      @member = Member.new(member_params)

      respond_to do |format|
        if @member.save
          format.html { redirect_to admin_room_member_path(@member), notice: t('.created') }
          format.json { render :show, status: :created, location: @member }
        else
          format.html { render :new }
          format.json { render json: @member.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /members/1
    # PATCH/PUT /members/1.json
    def update
      remove_blank_password_for(:member)

      respond_to do |format|
        if @member.update(member_params)
          format.html { redirect_to admin_room_member_path(@member), notice: t('.updated') }
          format.json { render :show, status: :ok, location: @member }
        else
          format.html { render :edit }
          format.json { render json: @member.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /members/1
    # DELETE /members/1.json
    def destroy
      @member.destroy
      respond_to do |format|
        format.html { redirect_to admin_room_members_url, notice: t('.destroyed') }
        format.json { head :no_content }
      end
    end

    private

    # Never trust parameters from the scary internet, only allow
    # the white list through.
    def member_params
      params.require(:member).permit(
        :first_name, :last_name, :email, :address, :postal_code,
        :city, :date_of_birth, :password
      )
    end
  end
end

app/controllers/admin_room/membership_forms_controller.rb
# frozen_string_literal: true

module AdminRoom
  class MembershipFormsController < AdminRoomController
    load_and_authorize_resource

    # GET /membership_forms
    # GET /membership_forms.json
    def index
      @membership_forms = MembershipForm.order(:title).page
    end

    # GET /membership_forms/1
    # GET /membership_forms/1.json
    def show
    end

    # GET /membership_forms/new
    def new
      @membership_form = MembershipForm.new
    end

    # GET /membership_forms/1/edit
    def edit
    end

    # POST /membership_forms
    # POST /membership_forms.json
    def create
      @membership_form = MembershipForm.new(membership_form_params)

      respond_to do |format|
        if @membership_form.save
          format.html { redirect_to admin_room_membership_form_path(@membership_form), notice: t('.created') }
          format.json { render :show, status: :created, location: @membership_form }
        else
          format.html { render :new }
          format.json { render json: @membership_form.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /membership_forms/1
    # PATCH/PUT /membership_forms/1.json
    def update
      respond_to do |format|
        if @membership_form.update(membership_form_params)
          format.html { redirect_to admin_room_membership_form_path(@membership_form), notice: t('.updated') }
          format.json { render :show, status: :ok, location: @membership_form }
        else
          format.html { render :edit }
          format.json { render json: @membership_form.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /membership_forms/1
    # DELETE /membership_forms/1.json
    def destroy
      @membership_form.destroy
      respond_to do |format|
        format.html { redirect_to admin_room_membership_forms_url, notice: t('.destroyed') }
        format.json { head :no_content }
      end
    end

    private

    # Never trust parameters from the scary internet,
    # only allow the white list through.
    def membership_form_params
      params.require(:membership_form).permit(:title, :content)
    end
  end
end

app/controllers/admin_room/memberships_controller.rb
# frozen_string_literal: true

module AdminRoom
  class MembershipsController < AdminRoomController
    load_and_authorize_resource :member
    load_and_authorize_resource :membership, through: :member

    # GET /members/1/memberships/1
    # GET /members/1/memberships/1.json
    def show
    end

    # GET /members/1/memberships/new
    def new
      @membership = Membership.new
    end

    # GET /members/1/memberships/1/edit
    def edit
    end

    # POST /members/1/memberships
    # POST /members/1/memberships.json
    def create
      @membership = Membership.new(membership_params.merge(member: @member))

      respond_to do |format|
        if @membership.save
          format.html { redirect_to admin_room_member_membership_path(id: @membership.id, member_id: @member.id), notice: t('.created') }
          format.json { render :show, status: :created, location: @membership }
        else
          format.html { render :new }
          format.json { render json: @membership.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /members/1/memberships/1
    # PATCH/PUT /members/1/memberships/1.json
    def update
      respond_to do |format|
        if @membership.update(membership_params)
          format.html { redirect_to admin_room_member_membership_path(id: @membership.id, member_id: @member.id), notice: t('.updated') }
          format.json { render :show, status: :ok, location: @membership }
        else
          format.html { render :edit }
          format.json { render json: @membership.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /members/1/memberships/1
    # DELETE /members/1/memberships/1.json
    def destroy
      @membership.destroy
      respond_to do |format|
        format.html { redirect_to admin_room_member_path(@member), notice: t('.destroyed') }
        format.json { head :no_content }
      end
    end

    private

    # Never trust parameters from the scary internet,
    # only allow the white list through.
    def membership_params
      params.require(:membership).permit(:membershiped_at, :membership_form_id)
    end
  end
end

app/controllers/admin_room/payments_controller.rb
# frozen_string_literal: true

module AdminRoom
  class PaymentsController < AdminRoomController
    load_and_authorize_resource :subscription
    load_and_authorize_resource :payment, through: :subscription

    # GET /subscriptions/1/payments/1
    # GET /subscriptions/1/payments/1.json
    def show
    end

    # GET /subscriptions/1/payments/new
    def new
      @payment = Payment.new
    end

    # GET /subscriptions/1/payments/1/edit
    def edit
    end

    # POST /subscriptions/1/payments
    # POST /subscriptions/1/payments.json
    def create
      @payment = Payment.new(payment_params.merge(subscription: @subscription))

      respond_to do |format|
        if @payment.save
          format.html { redirect_to admin_room_subscription_payment_path(id: @payment.id, subscription_id: @subscription.id), notice: t('.created') }
          format.json { render :show, status: :created }
        else
          format.html { render :new }
          format.json { render json: @payment.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /subscriptions/1/payments/1
    # PATCH/PUT /subscriptions/1/payments/1.json
    def update
      respond_to do |format|
        if @payment.update(payment_params)
          format.html { redirect_to admin_room_subscription_payment_path(id: @payment.id, subscription_id: @subscription.id), notice: t('.updated') }
          format.json { render :show, status: :ok }
        else
          format.html { render :edit }
          format.json { render json: @payment.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /subscriptions/1/payments/1
    # DELETE /subscriptions/1/payments/1.json
    def destroy
      @payment.destroy
      respond_to do |format|
        format.html { redirect_to admin_room_subscription_path(@subscription), notice: t('.destroyed') }
        format.json { head :no_content }
      end
    end

    private

    # Never trust parameters from the scary internet,
    # only allow the white list through.
    def payment_params
      params.require(:payment).permit(:payed_at, :amount, :means)
    end
  end
end

app/controllers/admin_room/producers_controller.rb
# frozen_string_literal: true

module AdminRoom
  class ProducersController < AdminRoomController
    load_and_authorize_resource

    # GET /producers
    # GET /producers.json
    def index
      @producers = Producer.order(:name).page
    end

    # GET /producers/1
    # GET /producers/1.json
    def show
    end

    # GET /producers/new
    def new
      @producer = Producer.new
    end

    # GET /producers/1/edit
    def edit
    end

    # POST /producers
    # POST /producers.json
    def create
      @producer = Producer.new(producer_params)

      respond_to do |format|
        if @producer.save
          format.html { redirect_to admin_room_producer_path(@producer), notice: t('.created') }
          format.json { render :show, status: :created, location: @producer }
        else
          format.html { render :new }
          format.json { render json: @producer.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /producers/1
    # PATCH/PUT /producers/1.json
    def update
      respond_to do |format|
        if @producer.update(producer_params)
          format.html { redirect_to admin_room_producer_path(@producer), notice: t('.updated') }
          format.json { render :show, status: :ok, location: @producer }
        else
          format.html { render :edit }
          format.json { render json: @producer.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /producers/1
    # DELETE /producers/1.json
    def destroy
      @producer.destroy
      respond_to do |format|
        format.html { redirect_to admin_room_producers_url, notice: t('.destroyed') }
        format.json { head :no_content }
      end
    end

    private

    # Never trust parameters from the scary internet, only allow
    # the white list through.
    def producer_params
      params.require(:producer).permit(
        :name, :email_address, :address, :postal_code, :city
      )
    end
  end
end

app/controllers/admin_room/welcome_controller.rb
# frozen_string_literal: true

module AdminRoom
  class WelcomeController < AdminRoomController
    def index
    end
  end
end

app/controllers/admin_room_controller.rb
# frozen_string_literal: true

class AdminRoomController < ApplicationController
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    Rails.logger.debug "Access denied on #{exception.action}"\
      " #{exception.subject.inspect}"
    raise
  end

  layout 'admin_room/layouts/application'
end

app/views/admin_room/members/_form.html.erb
<%= form_with(model: [:admin_room, member], local: true) do |form| %>
  <%= render 'shared/errors', errors: member.errors %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :date_of_birth %>
    <%= form.date_field :date_of_birth, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, class: 'form-control' %>
  </div>
  <%= form.submit t('actions.save'), class: 'btn btn-primary' %>
<% end %>

app/views/admin_room/members/edit.html.erb
<div class="d-flex align-items-center mb-3">
  <h1 class="h1 mr-2"><%= @member.full_name %></h1>
  <%= link_to t('actions.cancel'), admin_room_member_path(@member), class: 'btn btn-light' %>
</div>

<%= render 'form', member: @member %>

app/views/admin_room/members/index.html.erb
<div class="d-flex align-items-center mb-3">
  <h1 class="h1 mr-2"><%= t('members.list') %></h1>
  <%= link_to(t('members.new'), new_admin_room_member_path, class: 'btn btn-primary') if can? :create, Member %>
</div>

<table class="table table-sm">
  <thead>
    <tr>
      <th></th>
      <th><%= t('activerecord.attributes.member.date_of_birth') %></th>
      <th><%= t('activerecord.attributes.member.email') %></th>
      <th><%= t('activerecord.attributes.member.postal_code') %></th>
      <th><%= t('activerecord.attributes.member.city') %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.full_name, admin_room_member_path(member) %></td>
        <td><%= humanize_dt member.date_of_birth %></td>
        <td><%= member.email %></td>
        <td><%= member.postal_code %></td>
        <td><%= member.city %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @members %>

app/views/admin_room/members/new.html.erb
<div class="d-flex align-items-center mb-3">
  <h1 class="h1 mr-2"><%= t('members.new') %></h1>
  <%= link_to t('actions.back_to_the_list_html'), admin_room_members_path, class: 'btn btn-light' %>
</div>

<%= render 'form', member: @member %>

app/views/admin_room/members/show.html.erb
<div class="d-flex align-items-center mb-3">
  <h1 class="h1 mr-2"><%= @member.full_name %></h1>
  <%= link_to(t('actions.edit'), edit_admin_room_member_path(@member), class: 'btn btn-primary') if can? :update, @member %>
  <%= link_to(t('actions.delete'), admin_room_member_path(@member), method: :delete, data: { confirm: t('actions.sure?') }, class: 'ml-1 btn btn-danger') if can? :destroy, @member %>
  <%= link_to t('actions.back_to_the_list_html'), admin_room_members_path, class: 'ml-1 btn btn-light' %>
</div>

<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="true"><%= t('members.profile') %></a>
    <a class="nav-item nav-link" id="nav-memberships-tab" data-toggle="tab" href="#nav-memberships" role="tab" aria-controls="nav-memberships" aria-selected="true"><%= t('members.memberships') %></a>
    <a class="nav-item nav-link" id="nav-security-tab" data-toggle="tab" href="#nav-security" role="tab" aria-controls="nav-security" aria-selected="true"><%= t('members.security') %></a>
  </div>
</nav>

<div class="tab-content mt-3" id="nav-tabContent">
  <div class="tab-pane show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
    <dl class="row">
      <dt class="col-sm-3"><%= t('activerecord.attributes.member.date_of_birth') %></dt>
      <dd class="col-sm-9"><%= humanize_dt @member.date_of_birth %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.member.email') %></dt>
      <dd class="col-sm-9"><%= @member.email %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.member.address') %></dt>
      <dd class="col-sm-9"><%= @member.address %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.member.postal_code') %></dt>
      <dd class="col-sm-9"><%= @member.postal_code %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.member.city') %></dt>
      <dd class="col-sm-9"><%= @member.city %></dd>
    </dl>
  </div>
  <div class="tab-pane show" id="nav-memberships" role="tabpanel" aria-labelledby="nav-memberships-tab">
    <%= link_to(t('memberships.new'), new_admin_room_member_membership_path(member_id: @member.id), class: 'mb-2 btn btn-primary') if can? :create, Membership %>
    <table class="table table-sm">
      <thead>
        <tr>
          <th><%= t('activerecord.attributes.membership.membership_form_id') %></th>
          <th><%= t('activerecord.attributes.membership.membershiped_at') %></th>
          <th class="text-center"><%= t('memberships.member_signature') %></th>
        </tr>
      </thead>
      <tbody>
        <% @member.memberships.each do |membership| %>
          <tr>
            <td><%= link_to membership.membership_form.title, admin_room_member_membership_path(id: membership.id, member_id: membership.member_id) %></td>
            <td><%= humanize_dt membership.membershiped_at %></td>
            <td class="text-center"><%= humanize_bool membership.signed_by_the_member? %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="tab-pane show" id="nav-security" role="tabpanel" aria-labelledby="nav-security-tab">
    <dl class="row">
      <dt class="col-sm-3"><%= t('activerecord.attributes.user.sign_in_count') %></dt>
      <dd class="col-sm-9"><%= @member.sign_in_count %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.user.failed_attempts') %></dt>
      <dd class="col-sm-9"><%= @member.failed_attempts %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.user.current_sign_in_at') %></dt>
      <dd class="col-sm-9"><%= humanize_dt @member.current_sign_in_at %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.user.current_sign_in_ip') %></dt>
      <dd class="col-sm-9"><%= @member.current_sign_in_ip %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.user.last_sign_in_at') %></dt>
      <dd class="col-sm-9"><%= humanize_dt @member.last_sign_in_at %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.user.last_sign_in_ip') %></dt>
      <dd class="col-sm-9"><%= @member.last_sign_in_ip %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.user.locked_at') %></dt>
      <dd class="col-sm-9"><%= humanize_dt @member.locked_at %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.user.confirmed_at') %></dt>
      <dd class="col-sm-9"><%= humanize_dt @member.confirmed_at %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.user.updated_at') %></dt>
      <dd class="col-sm-9"><%= humanize_dt @member.updated_at %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.user.created_at') %></dt>
      <dd class="col-sm-9"><%= humanize_dt @member.created_at %></dd>
    </dl>
  </div>
</div>