config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin_room do
    resources :users
    resources :member_registration_requests, only: %i[index show] do
      put :accept, on: :member
      put :refuse, on: :member
    end
    resources :members do
      resources :memberships, except: %i[index]
    end
    resources :membership_forms
    resources :subscriptions, except: %i[edit] do
      get :preview, on: :member
      resources :payments, except: %i[index]
    end
    resources :producers do
      resources :contracts, except: %i[index]
    end

    root to: 'welcome#index'
  end

  namespace :member_room do
    root to: 'welcome#index'
    resources :subscriptions, only: %i[index show]
  end

  devise_for :users, path: 'admin_room'
  devise_for :members, path: 'member_room'

  delete :members_sign_up, to: 'members_sign_up#destroy'
  scope :members_sign_up, as: :members_sign_up do
    get :step_1, to: 'members_sign_up#step_1'
    post :step_1, to: 'members_sign_up#save_step_1'
    get :step_2, to: 'members_sign_up#step_2'
    patch :step_2, to: 'members_sign_up#save_step_2'
    get :step_3, to: 'members_sign_up#step_3'
    patch :step_3, to: 'members_sign_up#save_step_3'
    get :step_4, to: 'members_sign_up#step_4'
  end

  root to: 'welcome#index'
end

app/controllers/admin_room/contracts_controller.rb
# frozen_string_literal: true

module AdminRoom
  class ContractsController < AdminRoomController
    load_and_authorize_resource :producer
    load_and_authorize_resource :contract, through: :producer

    # GET /producers/1/contracts/1
    # GET /producers/1/contracts/1.json
    def show
    end

    # GET /producers/1/contracts/new
    def new
      @contract = Contract.new
    end

    # GET /producers/1/contracts/1/edit
    def edit
    end

    # POST /producers/1/contracts
    # POST /producers/1/contracts.json
    def create
      @contract = Contract.new(contract_params.merge(producer: @producer))

      respond_to do |format|
        if @contract.save
          format.html { redirect_to admin_room_producer_contract_path(id: @contract.id, producer_id: @producer.id), notice: t('.created') }
          format.json { render :show, status: :created, location: @contract }
        else
          format.html { render :new }
          format.json { render json: @contract.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /producers/1/contracts/1
    # PATCH/PUT /producers/1/contracts/1.json
    def update
      respond_to do |format|
        if @contract.update(contract_params)
          format.html { redirect_to admin_room_producer_contract_path(id: @contract.id, producer_id: @producer.id), notice: t('.updated') }
          format.json { render :show, status: :ok, location: @contract }
        else
          format.html { render :edit }
          format.json { render json: @contract.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /producers/1/contracts/1
    # DELETE /producers/1/contracts/1.json
    def destroy
      @contract.destroy
      respond_to do |format|
        format.html { redirect_to admin_room_producer_path(@producer), notice: t('.destroyed') }
        format.json { head :no_content }
      end
    end

    private

    # Never trust parameters from the scary internet, only allow
    # the white list through.
    def contract_params
      params.require(:contract).permit(:title, :content)
    end
  end
end

app/controllers/admin_room/member_registration_requests_controller.rb
# frozen_string_literal: true

module AdminRoom
  class MemberRegistrationRequestsController < AdminRoomController
    load_and_authorize_resource

    # GET /member_registration_requests
    # GET /member_registration_requests.json
    def index
      @member_registration_requests = MemberRegistrationRequest.not_accepted_or_refused_yet
                                                               .order(created_at: :desc)
                                                               .page
    end

    # GET /member_registration_requests/1
    # GET /member_registration_requests/1.json
    def show
    end

    # PUT /member_registration_requests/1/accept
    # PUT /member_registration_requests/1/accept.json
    def accept # rubocop:disable Metrics/MethodLength
      respond_to do |format|
        if @member_registration_request.accept(user: current_user)
          format.html { redirect_to admin_room_member_registration_request_path(id: @member_registration_request.id), notice: t('.accepted') }
          format.json { render :show, status: :ok, location: @member_registration_request }
        else
          format.html do
            flash[:alert] = @member_registration_request.errors.full_messages.join(', ')
            render :show
          end
          format.json { render json: @member_registration_request.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /member_registration_requests/1/refuse
    # PUT /member_registration_requests/1/refuse.json
    def refuse # rubocop:disable Metrics/MethodLength
      respond_to do |format|
        if @member_registration_request.refuse(user: current_user)
          format.html { redirect_to admin_room_member_registration_request_path(id: @member_registration_request.id), notice: t('.refused') }
          format.json { render :show, status: :ok, location: @member_registration_request }
        else
          format.html do
            flash[:alert] = @member_registration_request.errors.full_messages.join(', ')
            render :show
          end
          format.json { render json: @member_registration_request.errors, status: :unprocessable_entity }
        end
      end
    end
  end
end

app/controllers/admin_room/members_controller.rb
# frozen_string_literal: true

module AdminRoom
  class MembersController < AdminRoomController
    include RemoveBlankPasswordConcern

    load_and_authorize_resource

    # GET /members
    # GET /members.json
    def index
      query = params[:q]

      @members = if query.present?
                   Member.ransack(name_cont: query).result(distinct: true).page
                 else
                   Member.order(:first_name).page
                 end
    end

    # GET /members/1
    # GET /members/1.json
    def show
    end

    # GET /members/new
    def new
      @member = Member.new
    end

    # GET /members/1/edit
    def edit
    end

    # POST /members
    # POST /members.json
    def create
      @member = Member.new(member_params)

      respond_to do |format|
        if @member.save
          format.html { redirect_to admin_room_member_path(@member), notice: t('.created') }
          format.json { render :show, status: :created, location: @member }
        else
          format.html { render :new }
          format.json { render json: @member.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /members/1
    # PATCH/PUT /members/1.json
    def update
      remove_blank_password_for(:member)

      respond_to do |format|
        if @member.update(member_params)
          format.html { redirect_to admin_room_member_path(@member), notice: t('.updated') }
          format.json { render :show, status: :ok, location: @member }
        else
          format.html { render :edit }
          format.json { render json: @member.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /members/1
    # DELETE /members/1.json
    def destroy
      @member.destroy
      respond_to do |format|
        format.html { redirect_to admin_room_members_url, notice: t('.destroyed') }
        format.json { head :no_content }
      end
    end

    private

    # Never trust parameters from the scary internet, only allow
    # the white list through.
    def member_params
      params.require(:member).permit(
        :first_name, :last_name, :email, :address, :postal_code,
        :city, :date_of_birth, :password
      )
    end
  end
end

app/controllers/admin_room/membership_forms_controller.rb
# frozen_string_literal: true

module AdminRoom
  class MembershipFormsController < AdminRoomController
    load_and_authorize_resource

    # GET /membership_forms
    # GET /membership_forms.json
    def index
      @membership_forms = MembershipForm.order(:title).page
    end

    # GET /membership_forms/1
    # GET /membership_forms/1.json
    def show
    end

    # GET /membership_forms/new
    def new
      @membership_form = MembershipForm.new
    end

    # GET /membership_forms/1/edit
    def edit
    end

    # POST /membership_forms
    # POST /membership_forms.json
    def create
      @membership_form = MembershipForm.new(membership_form_params)

      respond_to do |format|
        if @membership_form.save
          format.html { redirect_to admin_room_membership_form_path(@membership_form), notice: t('.created') }
          format.json { render :show, status: :created, location: @membership_form }
        else
          format.html { render :new }
          format.json { render json: @membership_form.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /membership_forms/1
    # PATCH/PUT /membership_forms/1.json
    def update
      respond_to do |format|
        if @membership_form.update(membership_form_params)
          format.html { redirect_to admin_room_membership_form_path(@membership_form), notice: t('.updated') }
          format.json { render :show, status: :ok, location: @membership_form }
        else
          format.html { render :edit }
          format.json { render json: @membership_form.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /membership_forms/1
    # DELETE /membership_forms/1.json
    def destroy
      @membership_form.destroy
      respond_to do |format|
        format.html { redirect_to admin_room_membership_forms_url, notice: t('.destroyed') }
        format.json { head :no_content }
      end
    end

    private

    # Never trust parameters from the scary internet,
    # only allow the white list through.
    def membership_form_params
      params.require(:membership_form).permit(:title, :content)
    end
  end
end

app/controllers/admin_room/memberships_controller.rb
# frozen_string_literal: true

module AdminRoom
  class MembershipsController < AdminRoomController
    load_and_authorize_resource :member
    load_and_authorize_resource :membership, through: :member

    # GET /members/1/memberships/1
    # GET /members/1/memberships/1.json
    def show
    end

    # GET /members/1/memberships/new
    def new
      @membership = Membership.new
    end

    # GET /members/1/memberships/1/edit
    def edit
    end

    # POST /members/1/memberships
    # POST /members/1/memberships.json
    def create
      @membership = Membership.new(membership_params.merge(member: @member))

      respond_to do |format|
        if @membership.save
          format.html { redirect_to admin_room_member_membership_path(id: @membership.id, member_id: @member.id), notice: t('.created') }
          format.json { render :show, status: :created, location: @membership }
        else
          format.html { render :new }
          format.json { render json: @membership.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /members/1/memberships/1
    # PATCH/PUT /members/1/memberships/1.json
    def update
      respond_to do |format|
        if @membership.update(membership_params)
          format.html { redirect_to admin_room_member_membership_path(id: @membership.id, member_id: @member.id), notice: t('.updated') }
          format.json { render :show, status: :ok, location: @membership }
        else
          format.html { render :edit }
          format.json { render json: @membership.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /members/1/memberships/1
    # DELETE /members/1/memberships/1.json
    def destroy
      @membership.destroy
      respond_to do |format|
        format.html { redirect_to admin_room_member_path(@member), notice: t('.destroyed') }
        format.json { head :no_content }
      end
    end

    private

    # Never trust parameters from the scary internet,
    # only allow the white list through.
    def membership_params
      params.require(:membership).permit(:membershiped_at, :membership_form_id)
    end
  end
end

app/controllers/admin_room/payments_controller.rb
# frozen_string_literal: true

module AdminRoom
  class PaymentsController < AdminRoomController
    load_and_authorize_resource :subscription
    load_and_authorize_resource :payment, through: :subscription

    # GET /subscriptions/1/payments/1
    # GET /subscriptions/1/payments/1.json
    def show
    end

    # GET /subscriptions/1/payments/new
    def new
      @payment = Payment.new
    end

    # GET /subscriptions/1/payments/1/edit
    def edit
    end

    # POST /subscriptions/1/payments
    # POST /subscriptions/1/payments.json
    def create
      @payment = Payment.new(payment_params.merge(subscription: @subscription))

      respond_to do |format|
        if @payment.save
          format.html { redirect_to admin_room_subscription_payment_path(id: @payment.id, subscription_id: @subscription.id), notice: t('.created') }
          format.json { render :show, status: :created }
        else
          format.html { render :new }
          format.json { render json: @payment.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /subscriptions/1/payments/1
    # PATCH/PUT /subscriptions/1/payments/1.json
    def update
      respond_to do |format|
        if @payment.update(payment_params)
          format.html { redirect_to admin_room_subscription_payment_path(id: @payment.id, subscription_id: @subscription.id), notice: t('.updated') }
          format.json { render :show, status: :ok }
        else
          format.html { render :edit }
          format.json { render json: @payment.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /subscriptions/1/payments/1
    # DELETE /subscriptions/1/payments/1.json
    def destroy
      @payment.destroy
      respond_to do |format|
        format.html { redirect_to admin_room_subscription_path(@subscription), notice: t('.destroyed') }
        format.json { head :no_content }
      end
    end

    private

    # Never trust parameters from the scary internet,
    # only allow the white list through.
    def payment_params
      params.require(:payment).permit(:payed_at, :amount, :means)
    end
  end
end

app/controllers/admin_room/producers_controller.rb
# frozen_string_literal: true

module AdminRoom
  class ProducersController < AdminRoomController
    load_and_authorize_resource

    # GET /producers
    # GET /producers.json
    def index
      @producers = Producer.order(:name).page
    end

    # GET /producers/1
    # GET /producers/1.json
    def show
    end

    # GET /producers/new
    def new
      @producer = Producer.new
    end

    # GET /producers/1/edit
    def edit
    end

    # POST /producers
    # POST /producers.json
    def create
      @producer = Producer.new(producer_params)

      respond_to do |format|
        if @producer.save
          format.html { redirect_to admin_room_producer_path(@producer), notice: t('.created') }
          format.json { render :show, status: :created, location: @producer }
        else
          format.html { render :new }
          format.json { render json: @producer.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /producers/1
    # PATCH/PUT /producers/1.json
    def update
      respond_to do |format|
        if @producer.update(producer_params)
          format.html { redirect_to admin_room_producer_path(@producer), notice: t('.updated') }
          format.json { render :show, status: :ok, location: @producer }
        else
          format.html { render :edit }
          format.json { render json: @producer.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /producers/1
    # DELETE /producers/1.json
    def destroy
      @producer.destroy
      respond_to do |format|
        format.html { redirect_to admin_room_producers_url, notice: t('.destroyed') }
        format.json { head :no_content }
      end
    end

    private

    # Never trust parameters from the scary internet, only allow
    # the white list through.
    def producer_params
      params.require(:producer).permit(
        :name, :email_address, :address, :postal_code, :city
      )
    end
  end
end

app/controllers/admin_room/welcome_controller.rb
# frozen_string_literal: true

module AdminRoom
  class WelcomeController < AdminRoomController
    def index
    end
  end
end

app/controllers/admin_room_controller.rb
# frozen_string_literal: true

class AdminRoomController < ApplicationController
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    Rails.logger.debug "Access denied on #{exception.action}"\
      " #{exception.subject.inspect}"
    raise
  end

  layout 'admin_room/layouts/application'
end

app/controllers/member_room/subscriptions_controller.rb
# frozen_string_literal: true

module MemberRoom
  class SubscriptionsController < MemberRoomController
    load_and_authorize_resource through: :current_member

    # GET /subscriptions
    # GET /subscriptions.json
    def index
      @subscriptions = current_member.subscriptions.order(subscribed_at: :desc).page
    end

    # GET /subscriptions/1
    # GET /subscriptions/1.json
    def show
      render layout: false
    end
  end
end

app/views/admin_room/subscriptions/_form.html.erb
<div data-controller="subscription" data-members-url="<%= admin_room_members_path %>">
  <%= form_with(model: [:admin_room, subscription], local: true) do |form| %>
    <%= render 'shared/errors', errors: subscription.errors %>
    <%= form.hidden_field :member_id, data: { target: 'subscription.memberId', member: subscription.member&.full_name } %>
    <div class="form-group">
      <%= form.label :subscribed_at %>
      <%= form.datetime_local_field :subscribed_at, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :member_id %>
      <div class="input-group">
        <input placeholder="<%= t('subscriptions.member_placeholder') %>" class="form-control" data-target="subscription.member" data-action="keyup->subscription#findMember" type="text">
        <div class="input-group-append">
          <button class="btn btn-outline-secondary" type="button" data-action="subscription#unsetMember"><%= t('actions.cancel') %></button>
        </div>
      </div>
      <div class="card mt-1" data-target="subscription.members"></div>
    </div>
    <div class="form-group">
      <%= form.label :contract_id %>
      <%= form.collection_select(:contract_id, Contract.all, :id, :title, { include_blank: true }, { class: 'form-control' }) %>
    </div>
    <%= form.submit t('actions.save'), class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/admin_room/subscriptions/index.html.erb
<div class="d-flex align-items-center mb-3">
  <h1 class="h1 mr-2"><%= t('subscriptions.list') %></h1>
  <%= link_to(t('subscriptions.new'), new_admin_room_subscription_path, class: 'btn btn-primary') if can? :create, Subscription %>
</div>

<table class="table table-sm">
  <thead>
    <tr>
      <th></th>
      <th><%= t('activerecord.attributes.subscription.contract_id') %></th>
      <th><%= t('activerecord.attributes.contract.producer_id') %></th>
      <th><%= t('activerecord.attributes.subscription.member_id') %></th>
      <th><%= t('activerecord.attributes.subscription.subscribed_at') %></th>
      <th><%= t('subscriptions.member_signature') %></th>
      <th><%= t('subscriptions.producer_signature') %></th>
    </tr>
  </thead>
  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= link_to t('subscriptions.title', id: subscription.id), admin_room_subscription_path(subscription) %></td>
        <td><%= subscription.contract.title %></td>
        <td><%= subscription.contract.producer.name %></td>
        <td><%= subscription.member.full_name %></td>
        <td><%= humanize_dt subscription.subscribed_at %></td>
        <td class="text-center"><%= humanize_bool subscription.signed_by_the_member? %></td>
        <td class="text-center"><%= humanize_bool subscription.signed_by_the_producer? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @subscriptions %>

app/views/admin_room/subscriptions/new.html.erb
<div class="d-flex align-items-center mb-3">
  <h1 class="h1 mr-2"><%= t('subscriptions.new') %></h1>
  <%= link_to t('actions.back_to_the_list_html'), admin_room_subscriptions_path, class: 'btn btn-light' %>
</div>

<%= render 'form', subscription: @subscription %>

app/views/admin_room/subscriptions/preview.html.erb
<!doctype html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="turbolinks-visit-control" content="reload">
    <title><%= (content_for?(:title) ? content_for(:title) + ' / ' : '') + t('project.name') %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'admin_room/subscriptions_preview', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <header>
      <h1><%= @subscription.contract.title %></h1>
      <nav class="navbar navbar-expand-md fixed-bottom navbar-light bg-light">
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbars" aria-controls="navbars" aria-expanded="false" aria-label="<%= t('actions.toggle_menu') %>">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbars">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to t('actions.back_html'), admin_room_subscription_path(@subscription), class: 'btn btn-light' %>
              <a href="javascript:window.print()" class="btn btn-info"><%= t('actions.print') %></a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <main role="main" class="flex-shrink-0">
      <div class="container">
        <%= @subscription.contract.real_content(@subscription.member) %>
        <div class="row" data-controller="signature" data-update-url="<%= admin_room_subscription_path(@subscription, format: :json) %>">
          <div class="col-sm">
            <div id="producer" class="card text-center">
              <div class="card-body">
                <h5 class="card-title"><%= t('subscriptions.producer_signature') %></h5>
                <canvas class="border border-dark" data-signature="<%= @subscription.producer_signature_data_uri %>"></canvas>
              </div>
              <div class="card-footer">
                <button data-action="signature#editProducerSignature" class="btn btn-primary sign"><%= t('actions.sign') %></button>
                <button data-action="signature#saveProducerSignature" class="btn btn-primary save"><%= t('actions.save') %></button>
                <button data-action="signature#cancelProducerSignature" class="btn btn-secondary cancel"><%= t('actions.cancel') %></button>
              </div>
            </div>
          </div>
          <div class="col-sm">
            <div id="member" class="card text-center">
              <div class="card-body">
                <h5 class="card-title"><%= t('subscriptions.member_signature') %></h5>
                <canvas class="border border-dark" data-signature="<%= @subscription.member_signature_data_uri %>"></canvas>
              </div>
              <div class="card-footer">
                <button data-action="signature#editMemberSignature" class="btn btn-primary sign"><%= t('actions.sign') %></button>
                <button data-action="signature#saveMemberSignature" class="btn btn-primary save"><%= t('actions.save') %></button>
                <button data-action="signature#cancelMemberSignature" class="btn btn-secondary cancel"><%= t('actions.cancel') %></button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/admin_room/subscriptions/show.html.erb
<% unless @subscription.signed_by_the_member? %>
<div class="alert alert-warning" role="alert">
  <%=  t('subscriptions.member_signature_missing') %>
</div>
<% end %>

<% unless @subscription.signed_by_the_producer? %>
<div class="alert alert-warning" role="alert">
  <%=  t('subscriptions.producer_signature_missing') %>
</div>
<% end %>

<div class="d-flex align-items-center mb-3">
  <h1 class="h1 mr-2"><%= t('subscriptions.title', id: @subscription.id) %></h1>
  <%= link_to t('subscriptions.preview'), preview_admin_room_subscription_path(@subscription), class: 'btn btn-primary' %>
  <%= link_to(t('actions.delete'), admin_room_subscription_path(@subscription), method: :delete, data: { confirm: t('actions.sure?') }, class: 'ml-1 btn btn-danger') if can? :destroy, @subscription %>
  <%= link_to t('actions.back_to_the_list_html'), admin_room_subscriptions_path, class: 'ml-1 btn btn-light' %>
</div>

<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-info-tab" data-toggle="tab" href="#nav-info" role="tab" aria-controls="nav-info" aria-selected="true"><%= t('subscriptions.info') %></a>
    <a class="nav-item nav-link" id="nav-payments-tab" data-toggle="tab" href="#nav-payments" role="tab" aria-controls="nav-payments" aria-selected="true"><%= t('subscriptions.payments') %></a>
  </div>
</nav>

<div class="tab-content mt-3" id="nav-tabContent">
  <div class="tab-pane show active" id="nav-info" role="tabpanel" aria-labelledby="nav-info-tab">
    <dl class="row">
      <dt class="col-sm-3"><%= t('activerecord.attributes.subscription.subscribed_at') %></dt>
      <dd class="col-sm-9"><%= humanize_dt @subscription.subscribed_at %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.subscription.member_id') %></dt>
      <dd class="col-sm-9"><%= @subscription.member.full_name %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.subscription.contract_id') %></dt>
      <dd class="col-sm-9"><%= @subscription.contract.title %></dd>
      <dt class="col-sm-3"><%= t('activerecord.attributes.contract.producer_id') %></dt>
      <dd class="col-sm-9"><%= @subscription.contract.producer.name %></dd>
      <dt class="col-sm-3"><%= t('subscriptions.member_signature') %></dt>
      <dd class="col-sm-9"><%= humanize_dt @subscription.member_accepted_at %></dd>
      <dt class="col-sm-3"><%= t('subscriptions.producer_signature') %></dt>
      <dd class="col-sm-9"><%= humanize_dt @subscription.producer_accepted_at %></dd>
    </dl>
  </div>
  <div class="tab-pane show" id="nav-payments" role="tabpanel" aria-labelledby="nav-payments-tab">
    <%= link_to t('payments.new'), new_admin_room_subscription_payment_path(subscription_id: @subscription.id), class: 'btn btn-primary mb-3' %>
    <table class="table table-sm">
      <thead>
        <tr>
          <th></th>
          <th><%= t('activerecord.attributes.payment.payed_at') %></th>
          <th><%= t('activerecord.attributes.payment.means') %></th>
          <th><%= t('activerecord.attributes.payment.amount') %></th>
        </tr>
      </thead>
      <tbody>
      <% @subscription.payments.each do |payment| %>
      <tr>
        <td><%= link_to t('payments.title', id: payment.id), admin_room_subscription_payment_path(subscription_id: @subscription.id) %></td>
        <td><%= humanize_dt payment.payed_at, format: :short %></td>
        <td><%= humanize_payment_means payment.means %></td>
        <td><%= humanized_money_with_symbol payment.amount %></td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>